language: python
python:
  - "2.7"
addons:
  postgresql: "9.3"
services:
  - rabbitmq 
before_install: 
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - wget http://stoqs.mbari.org/terrain/bin/grdtrack -O grdtrack
  - chmod +x grdtrack
env:
  - DJANGO=1.7
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
  # Coverage packages are on my binstar channel
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - pip install -r requirements/ci.txt
before_script:
  - psql -c 'CREATE DATABASE template_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d template_postgis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d template_postgis
  - psql -c 'ALTER ROLE travis SUPERUSER;' -U postgres
  - psql -c '\du' -U postgres -d template_postgis
script:  
  - ./test.sh
after_script:
  - COVERALLS_REPO_TOKEN=B9qmcqI4Yq9CR0PkjYmy4eYQoJa3mdKDw coveralls --base_dir stoqs
notifications:
  email:
    on_success: change
    on_failure: always
