language: python
dist: precise
python:
  - "3.6"
addons:
  postgresql: "9.4"
  firefox: "49.0"
services:
  - rabbitmq 
before_install: 
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - export HDF5_DIR=/home/travis/miniconda3/
  - export NETCDF4_DIR=/home/travis/miniconda3/
  - export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3
  - export TERM=xterm
  - conda update --yes conda
  - wget -q -N https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz --directory /home/travis/miniconda3/bin
env:
  - DJANGO=1.10
install:
  - conda install --yes --verbose python=3.6 hdf4 hdf5 netcdf4 atlas numpy scipy matplotlib nose python-dateutil statsmodels
  - conda install --yes -c omnia python-coveralls=2.9.1
  - pip install --upgrade pip
  - pip install -r requirements/travis-ci.txt
before_script:
  - psql -c 'ALTER ROLE travis SUPERUSER;' -U postgres
  - export DATABASE_URL="postgis://travis:@127.0.0.1:5432/stoqs"
  - wget http://ftp.mozilla.org/pub/firefox/releases/52.0/linux-x86_64/en-US/firefox-52.0.tar.bz2
  - tar xvjf firefox-52.0.tar.bz2
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver  
  - export PATH=$PWD/firefox:$PATH:$PWD/geckodriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo rabbitmqctl add_user stoqs stoqs
  - sudo rabbitmqctl add_vhost stoqs
  - sudo rabbitmqctl set_permissions -p stoqs stoqs ".*" ".*" ".*"
script:  
  - ./test.sh CHANGEME load noextraload
after_script:
  - travis_wait 5 COVERALLS_REPO_TOKEN=W1wSPd6A9HGyoPWXGlyZ6mxkGsZR7BybT coveralls --base_dir stoqs
notifications:
  email:
    on_success: change
    on_failure: always
