version: '2'

services:
  rabbitmq:
    volumes:
      - ${STOQS_VOLS_DIR}/rabbitmq:/var/lib/rabbitmq

    ports:
      - "${STOQS_RABBITMQ_PORT}:4369"

    environment:
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - STOQS_RABBITMQ_PORT=${STOQS_RABBITMQ_PORT}

    container_name: stoqs-rabbitmq
    image: rabbitmq:3

  postgis:
    volumes:
      - ${STOQS_VOLS_DIR}/pgdata:/var/lib/postgresql/data

    ports:
      - "${STOQS_POSTGRES_PORT}:5432"

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - STOQSADM_PASS=${STOQSADM_PASS}

    container_name: stoqs-postgis
    image: mbari/stoqs-postgis:0.0.1

#  stoqs:
#    #volumes:
#    #  - ...
#
#    ports:
#      - "${STOQS_HOST_PORT}:8080"
#
#    environment:
#      - ???=???
#      - ???=???
#
#    image: mbari/stoqs:0.0.1
#    container_name: stoqs
#    depends_on:
#      - postgis
#      - rabbitmq
#
