version: '2'

services:

  postgis:
    build:
        context: .
        dockerfile: Dockerfile-postgis
    volumes:
      - ${STOQS_VOLS_DIR}/pgdata:/var/lib/postgresql/data
    ports:
      - "${STOQS_HOST_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - STOQSADM_PASS=${STOQSADM_PASS}
    container_name: stoqs-postgis
    env_file:
      - ./.env

  mapserver:
    build:
        context: .
        dockerfile: Dockerfile-mapserver
    volumes:
      - ${STOQS_VOLS_DIR}/maps:/maps:ro
    ports:
      - "${STOQS_HOST_MAPSERVER_PORT}:7000"
    container_name: stoqs-mapserver
    env_file:
      - ./.env

  stoqs:
    build:
        context: ..
        dockerfile: Dockerfile-stoqs
    volumes:
      - ${STOQS_VOLS_DIR}/maps:/dev/shm
      - ${STOQS_VOLS_DIR}/stoqs_root:/root
      - ${STOQS_VOLS_DIR}/nginx:/usr/share/nginx
    ports:
      - "${STOQS_HOST_DJANGO_PORT}:8000"
      - "${STOQS_HOST_HTTP_PORT}:80"
      # For testing serving directly from uwsgi
      - 9090:9090
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_SUPERUSER_URL=${DATABASE_SUPERUSER_URL}
      # Map STOQS_PGHOST to PGHOST, which sets default host for psql
      - PGHOST=${STOQS_PGHOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MAPSERVER_HOST=${STOQS_HOST}:${STOQS_HOST_MAPSERVER_PORT}
      - URL_MAPFILE_DIR=/maps
    container_name: stoqs
    expose:
      - "8000"
    depends_on:
      - mapserver
      - postgis
    env_file:
      - ./.env

  nginx:
    build:
        context: .
        dockerfile: Dockerfile-nginx
    volumes:
      - ${STOQS_VOLS_DIR}/static-files:/srv/static-files
    container_name: stoqs-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - stoqs
    env_file:
      - ./.env

