#
# Unfortunately I'm noticing issue https://github.com/docker/compose/issues/4337:
# docker-compose refuses to reflect updates to the mbari/stoqs-postgis image, even
# after explicitly removing any associated container (docker rm) and even using
# --force-recreate.
# The only solution at this point is not to use docker-compose but docker directly
# as indicated in the README.
# We can revisit this at some point.
#

version: '2'

services:
  rabbitmq:
    volumes:
      - $PWD/vols/rabbitmq:/var/lib/rabbitmq

    ports:
      - "${STOQS_RABBITMQ_PORT}:4369"

    environment:
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - STOQS_RABBITMQ_PORT=${STOQS_RABBITMQ_PORT}

    container_name: stoqs-rabbitmq
    image: rabbitmq:3

  postgis:
    volumes:
      - $PWD/vols/pgdata:/var/lib/postgresql/data

    ports:
      - "${STOQS_POSTGRES_PORT}:5432"

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - STOQSADM_PASS=${STOQSADM_PASS}

    container_name: stoqs-postgis
    image: mbari/stoqs-postgis:0.0.1

#  stoqs:
#    #volumes:
#    #  - ...
#
#    ports:
#      - "${STOQS_HOST_PORT}:8080"
#
#    environment:
#      - ???=???
#      - ???=???
#
#    image: mbari/stoqs:0.0.1
#    container_name: stoqs
#    depends_on:
#      - postgis
#      - rabbitmq
#
